version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quadro_scrap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/quadro_scrap
      - EMAIL_PEPPER=your-email-pepper-change-me
      - RESEND_API_KEY=your-resend-api-key
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
